import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_url: string | null;
          settings: Record<string, unknown>;
          subscription_tier: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo_url?: string | null;
          settings?: Record<string, unknown>;
          subscription_tier?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo_url?: string | null;
          settings?: Record<string, unknown>;
          subscription_tier?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: string;
          permissions: unknown[];
          invited_by: string | null;
          joined_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role?: string;
          permissions?: unknown[];
          invited_by?: string | null;
          joined_at?: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role?: string;
          permissions?: unknown[];
          invited_by?: string | null;
          joined_at?: string;
          is_active?: boolean;
        };
      };
      facilities: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string | null;
          type: string;
          description: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          coordinates: unknown | null;
          total_capacity: number | null;
          max_weight_capacity: number | null;
          has_dangerous_goods_storage: boolean;
          requires_certification: boolean;
          operating_hours: Record<string, unknown>;
          contact_name: string | null;
          contact_email: string | null;
          contact_phone: string | null;
          status: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          code?: string | null;
          type: string;
          description?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          coordinates?: unknown | null;
          total_capacity?: number | null;
          max_weight_capacity?: number | null;
          has_dangerous_goods_storage?: boolean;
          requires_certification?: boolean;
          operating_hours?: Record<string, unknown>;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          code?: string | null;
          type?: string;
          description?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          coordinates?: unknown | null;
          total_capacity?: number | null;
          max_weight_capacity?: number | null;
          has_dangerous_goods_storage?: boolean;
          requires_certification?: boolean;
          operating_hours?: Record<string, unknown>;
          contact_name?: string | null;
          contact_email?: string | null;
          contact_phone?: string | null;
          status?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      asset_categories: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string;
          description: string | null;
          icon: string | null;
          color: string | null;
          lifecycle_stages: unknown[];
          custom_fields: Record<string, unknown>;
          requires_certification: boolean;
          requires_maintenance: boolean;
          maintenance_interval_days: number;
          gas_type: string | null;
          standard_capacity: number | null;
          standard_pressure: number | null;
          unit_of_measure: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          code: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          lifecycle_stages?: unknown[];
          custom_fields?: Record<string, unknown>;
          requires_certification?: boolean;
          requires_maintenance?: boolean;
          maintenance_interval_days?: number;
          gas_type?: string | null;
          standard_capacity?: number | null;
          standard_pressure?: number | null;
          unit_of_measure?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          code?: string;
          description?: string | null;
          icon?: string | null;
          color?: string | null;
          lifecycle_stages?: unknown[];
          custom_fields?: Record<string, unknown>;
          requires_certification?: boolean;
          requires_maintenance?: boolean;
          maintenance_interval_days?: number;
          gas_type?: string | null;
          standard_capacity?: number | null;
          standard_pressure?: number | null;
          unit_of_measure?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      assets: {
        Row: {
          id: string;
          organization_id: string;
          category_id: string;
          asset_number: string;
          qr_code: string | null;
          barcode: string | null;
          serial_number: string | null;
          name: string | null;
          description: string | null;
          status: string;
          sub_status: string | null;
          current_facility_id: string | null;
          current_zone_id: string | null;
          current_custodian_id: string | null;
          ownership_type: string;
          owner_organization_id: string | null;
          purchase_date: string | null;
          purchase_price: number | null;
          warranty_expiry_date: string | null;
          insurance_provider: string | null;
          insurance_policy_number: string | null;
          insured_value: number | null;
          weight: number | null;
          dimensions: Record<string, unknown> | null;
          color: string | null;
          material: string | null;
          gas_type_id: string | null;
          capacity: number | null;
          max_pressure: number | null;
          current_fill_percentage: number | null;
          last_fill_date: string | null;
          last_hydrostatic_test: string | null;
          next_hydrostatic_test: string | null;
          model_number: string | null;
          manufacturer: string | null;
          manufactured_date: string | null;
          installation_date: string | null;
          health_score: number;
          risk_score: number;
          reliability_score: number;
          utilization_rate: number;
          lifecycle_stage: string;
          total_rental_days: number;
          total_distance_traveled_km: number;
          total_fills_cycles: number;
          iot_device_id: string | null;
          last_telemetry_at: string | null;
          telemetry_data: Record<string, unknown>;
          notes: string | null;
          custom_attributes: Record<string, unknown>;
          tags: string[];
          primary_photo_url: string | null;
          photos: unknown[];
          last_maintenance_at: string | null;
          next_maintenance_date: string | null;
          last_inspection_at: string | null;
          created_at: string;
          updated_at: string;
          deactivated_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          category_id: string;
          asset_number: string;
          qr_code?: string | null;
          barcode?: string | null;
          serial_number?: string | null;
          name?: string | null;
          description?: string | null;
          status?: string;
          sub_status?: string | null;
          current_facility_id?: string | null;
          current_zone_id?: string | null;
          current_custodian_id?: string | null;
          ownership_type?: string;
          owner_organization_id?: string | null;
          purchase_date?: string | null;
          purchase_price?: number | null;
          warranty_expiry_date?: string | null;
          insurance_provider?: string | null;
          insurance_policy_number?: string | null;
          insured_value?: number | null;
          weight?: number | null;
          dimensions?: Record<string, unknown> | null;
          color?: string | null;
          material?: string | null;
          gas_type_id?: string | null;
          capacity?: number | null;
          max_pressure?: number | null;
          current_fill_percentage?: number | null;
          last_fill_date?: string | null;
          last_hydrostatic_test?: string | null;
          next_hydrostatic_test?: string | null;
          model_number?: string | null;
          manufacturer?: string | null;
          manufactured_date?: string | null;
          installation_date?: string | null;
          health_score?: number;
          risk_score?: number;
          reliability_score?: number;
          utilization_rate?: number;
          lifecycle_stage?: string;
          total_rental_days?: number;
          total_distance_traveled_km?: number;
          total_fills_cycles?: number;
          iot_device_id?: string | null;
          last_telemetry_at?: string | null;
          telemetry_data?: Record<string, unknown>;
          notes?: string | null;
          custom_attributes?: Record<string, unknown>;
          tags?: string[];
          primary_photo_url?: string | null;
          photos?: unknown[];
          last_maintenance_at?: string | null;
          next_maintenance_date?: string | null;
          last_inspection_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deactivated_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          category_id?: string;
          asset_number?: string;
          qr_code?: string | null;
          barcode?: string | null;
          serial_number?: string | null;
          name?: string | null;
          description?: string | null;
          status?: string;
          sub_status?: string | null;
          current_facility_id?: string | null;
          current_zone_id?: string | null;
          current_custodian_id?: string | null;
          ownership_type?: string;
          owner_organization_id?: string | null;
          purchase_date?: string | null;
          purchase_price?: number | null;
          warranty_expiry_date?: string | null;
          insurance_provider?: string | null;
          insurance_policy_number?: string | null;
          insured_value?: number | null;
          weight?: number | null;
          dimensions?: Record<string, unknown> | null;
          color?: string | null;
          material?: string | null;
          gas_type_id?: string | null;
          capacity?: number | null;
          max_pressure?: number | null;
          current_fill_percentage?: number | null;
          last_fill_date?: string | null;
          last_hydrostatic_test?: string | null;
          next_hydrostatic_test?: string | null;
          model_number?: string | null;
          manufacturer?: string | null;
          manufactured_date?: string | null;
          installation_date?: string | null;
          health_score?: number;
          risk_score?: number;
          reliability_score?: number;
          utilization_rate?: number;
          lifecycle_stage?: string;
          total_rental_days?: number;
          total_distance_traveled_km?: number;
          total_fills_cycles?: number;
          iot_device_id?: string | null;
          last_telemetry_at?: string | null;
          telemetry_data?: Record<string, unknown>;
          notes?: string | null;
          custom_attributes?: Record<string, unknown>;
          tags?: string[];
          primary_photo_url?: string | null;
          photos?: unknown[];
          last_maintenance_at?: string | null;
          next_maintenance_date?: string | null;
          last_inspection_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deactivated_at?: string | null;
        };
      };
      customers: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          code: string | null;
          type: string;
          industry: string | null;
          description: string | null;
          website: string | null;
          primary_email: string | null;
          primary_phone: string | null;
          credit_limit: number | null;
          payment_terms: string;
          discount_percentage: number | null;
          tax_id: string | null;
          contract_id: string | null;
          contract_start_date: string | null;
          contract_end_date: string | null;
          pricing_tier: string;
          status: string;
          is_vip: boolean;
          notes: string | null;
          tags: string[];
          custom_fields: Record<string, unknown>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          code?: string | null;
          type?: string;
          industry?: string | null;
          description?: string | null;
          website?: string | null;
          primary_email?: string | null;
          primary_phone?: string | null;
          credit_limit?: number | null;
          payment_terms?: string;
          discount_percentage?: number | null;
          tax_id?: string | null;
          contract_id?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          pricing_tier?: string;
          status?: string;
          is_vip?: boolean;
          notes?: string | null;
          tags?: string[];
          custom_fields?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          code?: string | null;
          type?: string;
          industry?: string | null;
          description?: string | null;
          website?: string | null;
          primary_email?: string | null;
          primary_phone?: string | null;
          credit_limit?: number | null;
          payment_terms?: string;
          discount_percentage?: number | null;
          tax_id?: string | null;
          contract_id?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          pricing_tier?: string;
          status?: string;
          is_vip?: boolean;
          notes?: string | null;
          tags?: string[];
          custom_fields?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          organization_id: string;
          order_number: string;
          external_reference: string | null;
          customer_id: string;
          customer_location_id: string | null;
          status: string;
          sub_status: string | null;
          priority: string;
          is_emergency: boolean;
          order_date: string;
          requested_delivery_date: string | null;
          scheduled_delivery_date: string | null;
          actual_delivery_date: string | null;
          delivery_window_start: string | null;
          delivery_window_end: string | null;
          assigned_driver_id: string | null;
          assigned_vehicle_id: string | null;
          route_id: string | null;
          delivery_facility_id: string | null;
          total_items: number;
          total_quantity: number;
          total_weight: number | null;
          subtotal: number;
          tax_amount: number;
          discount_amount: number;
          total_amount: number;
          source_facility_id: string | null;
          is_recurring: boolean;
          recurring_frequency: string | null;
          parent_order_id: string | null;
          customer_notes: string | null;
          internal_notes: string | null;
          cancellation_reason: string | null;
          sla_due_date: string | null;
          sla_status: string;
          created_by: string | null;
          approved_by: string | null;
          approved_at: string | null;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
          cancelled_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          order_number: string;
          external_reference?: string | null;
          customer_id: string;
          customer_location_id?: string | null;
          status?: string;
          sub_status?: string | null;
          priority?: string;
          is_emergency?: boolean;
          order_date?: string;
          requested_delivery_date?: string | null;
          scheduled_delivery_date?: string | null;
          actual_delivery_date?: string | null;
          delivery_window_start?: string | null;
          delivery_window_end?: string | null;
          assigned_driver_id?: string | null;
          assigned_vehicle_id?: string | null;
          route_id?: string | null;
          delivery_facility_id?: string | null;
          total_items?: number;
          total_quantity?: number;
          total_weight?: number | null;
          subtotal?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          source_facility_id?: string | null;
          is_recurring?: boolean;
          recurring_frequency?: string | null;
          parent_order_id?: string | null;
          customer_notes?: string | null;
          internal_notes?: string | null;
          cancellation_reason?: string | null;
          sla_due_date?: string | null;
          sla_status?: string;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          order_number?: string;
          external_reference?: string | null;
          customer_id?: string;
          customer_location_id?: string | null;
          status?: string;
          sub_status?: string | null;
          priority?: string;
          is_emergency?: boolean;
          order_date?: string;
          requested_delivery_date?: string | null;
          scheduled_delivery_date?: string | null;
          actual_delivery_date?: string | null;
          delivery_window_start?: string | null;
          delivery_window_end?: string | null;
          assigned_driver_id?: string | null;
          assigned_vehicle_id?: string | null;
          route_id?: string | null;
          delivery_facility_id?: string | null;
          total_items?: number;
          total_quantity?: number;
          total_weight?: number | null;
          subtotal?: number;
          tax_amount?: number;
          discount_amount?: number;
          total_amount?: number;
          source_facility_id?: string | null;
          is_recurring?: boolean;
          recurring_frequency?: string | null;
          parent_order_id?: string | null;
          customer_notes?: string | null;
          internal_notes?: string | null;
          cancellation_reason?: string | null;
          sla_due_date?: string | null;
          sla_status?: string;
          created_by?: string | null;
          approved_by?: string | null;
          approved_at?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
          cancelled_at?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];

export type InsertTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];

export type UpdateTables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
