import { useUIStore } from '../stores/uiStore';

export const terminology = {
  es: {
    medical_oxygen: {
      assets: 'Cilindros y Activos',
      assetSingular: 'Cilindro/Equipo',
      assetDesc: 'Gestiona cilindros de oxígeno, concentradores y tanques criogénicos',
      categories: ['Cilindro de Oxígeno', 'Concentrador', 'Tanque Criogénico', 'Accesorios'],
      statusLabels: {
        available: 'Disponible',
        reserved: 'Reservado',
        in_transit: 'En Tránsito',
        delivered: 'Entregado',
        in_use: 'En Uso',
        maintenance: 'Mantenimiento',
        damaged: 'Dañado',
        lost: 'Perdido',
        retired: 'Retirado',
      },
      placeholderSearch: 'Buscar por ID, cilindro, número de serie o código QR...',
      dashboardTitle: 'Sistema Operativo de Logística Sanitaria',
      platformDesc: 'Plataforma empresarial para la gestión de activos médicos, cilindros de oxígeno y equipos con IA.',
    },
    bakery: {
      assets: 'Ingredientes y Hornos',
      assetSingular: 'Ingrediente/Equipo',
      assetDesc: 'Gestiona materias primas, productos horneados y maquinaria de cocina',
      categories: ['Materia Prima', 'Horno', 'Moldes', 'Productos Finales'],
      statusLabels: {
        available: 'En Stock',
        reserved: 'Asignado',
        in_transit: 'En Reparto',
        delivered: 'Entregado',
        in_use: 'En Proceso',
        maintenance: 'Limpieza/Calibración',
        damaged: 'Vencido/Dañado',
        lost: 'Merma',
        retired: 'Desechado',
      },
      placeholderSearch: 'Buscar por lote, ingrediente, maquinaria o código QR...',
      dashboardTitle: 'Sistema de Logística y Ventas de Panadería',
      platformDesc: 'Plataforma empresarial para la gestión de ingredientes, pedidos de panadería y distribución con IA.',
    },
    retail: {
      assets: 'Productos y Mercancía',
      assetSingular: 'Producto',
      assetDesc: 'Gestiona catálogo de artículos, inventario y mercadería',
      categories: ['Electrónica', 'Ropa y Calzado', 'Hogar y Decoración', 'Alimentos'],
      statusLabels: {
        available: 'Disponible para venta',
        reserved: 'Reservado / Carrito',
        in_transit: 'Enviado',
        delivered: 'Entregado',
        in_use: 'En Exhibición',
        maintenance: 'Revisión técnica',
        damaged: 'Defectuoso',
        lost: 'Extraviado',
        retired: 'Descontinuado',
      },
      placeholderSearch: 'Buscar por SKU, nombre de producto, categoría o código de barras...',
      dashboardTitle: 'Gestor de Ventas y Distribución Retail',
      platformDesc: 'Optimiza la logística de tus ventas, distribución de mercadería y control de inventarios con IA.',
    },
    services: {
      assets: 'Herramientas y Repuestos',
      assetSingular: 'Herramienta/Repuesto',
      assetDesc: 'Gestiona herramientas de trabajo, consumibles y vehículos de servicio',
      categories: ['Herramienta Eléctrica', 'Equipo de Medición', 'Repuestos', 'Consumibles'],
      statusLabels: {
        available: 'Disponible en Taller',
        reserved: 'Asignado a Técnico',
        in_transit: 'En Ruta de Servicio',
        delivered: 'Entregado a Cliente',
        in_use: 'En Operación',
        maintenance: 'Calibración / Service',
        damaged: 'Fuera de Servicio',
        lost: 'Perdido',
        retired: 'Descartado',
      },
      placeholderSearch: 'Buscar por herramienta, repuesto, código QR o técnico...',
      dashboardTitle: 'Administrador de Servicios Técnicos y Flotas',
      platformDesc: 'Plataforma para gestionar técnicos de campo, repuestos, herramientas y órdenes de servicio con IA.',
    },
    general: {
      assets: 'Inventario y Carga',
      assetSingular: 'Bulto/Palet',
      assetDesc: 'Gestiona palets, contenedores, paquetes y mercancía general',
      categories: ['Palet', 'Contenedor', 'Caja / Bulto', 'Maquinaria de Carga'],
      statusLabels: {
        available: 'En Almacén',
        reserved: 'Asignado a Ruta',
        in_transit: 'En Tránsito',
        delivered: 'Entregado',
        in_use: 'En Carga',
        maintenance: 'Inspección',
        damaged: 'Carga Dañada',
        lost: 'Sin Ubicar',
        retired: 'Retirado',
      },
      placeholderSearch: 'Buscar por número de guía, palet, contenedor o código QR...',
      dashboardTitle: 'Sistema Operativo de Logística y Carga',
      platformDesc: 'Gestión inteligente de flotas, contenedores, rutas y entregas de última milla con IA.',
    },
  },
  en: {
    medical_oxygen: {
      assets: 'Cylinders & Assets',
      assetSingular: 'Cylinder/Equipment',
      assetDesc: 'Manage oxygen cylinders, concentrators, and cryogenic tanks',
      categories: ['Oxygen Cylinder', 'Concentrator', 'Cryogenic Tank', 'Accessories'],
      statusLabels: {
        available: 'Available',
        reserved: 'Reserved',
        in_transit: 'In Transit',
        delivered: 'Delivered',
        in_use: 'In Use',
        maintenance: 'Maintenance',
        damaged: 'Damaged',
        lost: 'Lost',
        retired: 'Retired',
      },
      placeholderSearch: 'Search by ID, cylinder, serial number, or QR code...',
      dashboardTitle: 'Healthcare Logistics Operating System',
      platformDesc: 'Enterprise-grade platform for managing medical assets, oxygen cylinders, and equipment with AI.',
    },
    bakery: {
      assets: 'Ingredients & Equipment',
      assetSingular: 'Ingredient/Equipment',
      assetDesc: 'Manage raw materials, baked goods, and kitchen machinery',
      categories: ['Raw Material', 'Oven', 'Molds', 'Final Products'],
      statusLabels: {
        available: 'In Stock',
        reserved: 'Assigned',
        in_transit: 'Out for Delivery',
        delivered: 'Delivered',
        in_use: 'In Process',
        maintenance: 'Cleaning/Calibration',
        damaged: 'Expired/Damaged',
        lost: 'Wastage',
        retired: 'Discarded',
      },
      placeholderSearch: 'Search by batch, ingredient, machinery, or QR code...',
      dashboardTitle: 'Bakery Logistics & Sales System',
      platformDesc: 'Enterprise platform for managing ingredients, bakery orders, and distribution with AI.',
    },
    retail: {
      assets: 'Products & Merchandise',
      assetSingular: 'Product',
      assetDesc: 'Manage items catalog, inventory, and goods',
      categories: ['Electronics', 'Clothing & Shoes', 'Home & Decor', 'Groceries'],
      statusLabels: {
        available: 'Available for sale',
        reserved: 'Reserved / Cart',
        in_transit: 'Shipped',
        delivered: 'Delivered',
        in_use: 'On Display',
        maintenance: 'Technical Review',
        damaged: 'Defective',
        lost: 'Missing',
        retired: 'Discontinued',
      },
      placeholderSearch: 'Search by SKU, product name, category, or barcode...',
      dashboardTitle: 'Retail Sales & Distribution Manager',
      platformDesc: 'Optimize your sales logistics, product distribution, and inventory control with AI.',
    },
    services: {
      assets: 'Tools & Spare Parts',
      assetSingular: 'Tool/Spare Part',
      assetDesc: 'Manage work tools, consumables, and service vehicles',
      categories: ['Power Tool', 'Measuring Equipment', 'Spare Parts', 'Consumibles'],
      statusLabels: {
        available: 'Available in Workshop',
        reserved: 'Assigned to Tech',
        in_transit: 'On Service Route',
        delivered: 'Delivered to Client',
        in_use: 'In Operation',
        maintenance: 'Calibration / Service',
        damaged: 'Out of Service',
        lost: 'Lost',
        retired: 'Discarded',
      },
      placeholderSearch: 'Search by tool, spare part, QR code, or technician...',
      dashboardTitle: 'Technical Services & Fleet Administrator',
      platformDesc: 'Platform for managing field technicians, spare parts, tools, and service orders with AI.',
    },
    general: {
      assets: 'Inventory & Cargo',
      assetSingular: 'Package/Pallet',
      assetDesc: 'Manage pallets, containers, packages, and general merchandise',
      categories: ['Pallet', 'Container', 'Box / Package', 'Loading Machinery'],
      statusLabels: {
        available: 'In Warehouse',
        reserved: 'Assigned to Route',
        in_transit: 'In Transit',
        delivered: 'Delivered',
        in_use: 'In Loading',
        maintenance: 'Inspection',
        damaged: 'Cargo Damaged',
        lost: 'Unlocated',
        retired: 'Retired',
      },
      placeholderSearch: 'Search by tracking number, pallet, container, or QR code...',
      dashboardTitle: 'Logistics & Cargo Operating System',
      platformDesc: 'Smart management of fleets, containers, routes, and last-mile deliveries with AI.',
    },
  },
};

export function useTerminology() {
  const { language, businessType } = useUIStore();
  
  // Safely fallback to spanish / medical_oxygen if undefined
  const lang = (language === 'es' || language === 'en') ? language : 'es';
  const type = businessType || 'medical_oxygen';
  
  const t = terminology[lang][type] || terminology[lang]['medical_oxygen'];
  
  return {
    t,
    businessType: type,
  };
}
